---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
ms.openlocfilehash: 0e00adf736508e1bfc4f766eceda8c956411ec6e
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 02/17/2020
ms.locfileid: "77416639"
---
# <a name="c28105"></a>C28105

> Avviso C28105: la risorsa è in perdita a causa di un'eccezione

La risorsa specificata non viene liberata quando viene generata un'eccezione. L'istruzione specificata dal percorso può generare un'eccezione. Questo avviso è simile a Warning [C28103](../code-quality/c28103.md), con la differenza che in questo caso viene generata un'eccezione.

## <a name="example"></a>Esempio

Nell'esempio riportato di seguito il codice genera questo avviso:

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

Nell'esempio riportato di seguito il codice evita questo avviso:

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
